# Generated by Django 4.2.3 on 2023-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Not Available', max_length=200)),
                ('first_name', models.CharField(default='Not Available', max_length=150)),
                ('middle_initial', models.CharField(default='Not Available', max_length=150)),
                ('last_name', models.CharField(default='Not Available', max_length=150)),
                ('phone', models.BigIntegerField(default='0000000000')),
                ('address', models.CharField(default='Not Available', max_length=200)),
                ('country', models.CharField(default='Not Available', max_length=30)),
                ('city', models.CharField(default='Not Available', max_length=30)),
                ('state', models.CharField(default='Not Available', max_length=30)),
                ('age_range', models.CharField(default='Not Available', max_length=10)),
                ('income_range', models.CharField(default='Not Available', max_length=50)),
            ],
        ),
    ]
