# Generated by Django 4.2.3 on 2023-07-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGeneration', '0002_alter_persondata_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='country',
            new_name='county',
        ),
        migrations.AddField(
            model_name='persondata',
            name='ethnicity',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='persondata',
            name='hobbies',
            field=models.CharField(default='Not Available', max_length=200),
        ),
        migrations.AddField(
            model_name='persondata',
            name='home_owner',
            field=models.CharField(default='Not Available', max_length=20),
        ),
        migrations.AddField(
            model_name='persondata',
            name='language',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='persondata',
            name='likely_investor',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='persondata',
            name='martial_status',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AddField(
            model_name='persondata',
            name='neighbourhood',
            field=models.CharField(default='Not Available', max_length=200),
        ),
    ]
