# Generated by Django 4.2.3 on 2023-08-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailGeneration', '0002_emailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='targetPerson',
        ),
    ]
