# Generated by Django 4.2.3 on 2023-07-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailGeneration', '0003_rename_country_persondata_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondata',
            name='phone',
        ),
    ]
