# Generated by Django 4.2.3 on 2023-08-09 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailGeneration', '0003_remove_emailmodel_targetperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='sendAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
