# Generated by Django 4.2.3 on 2023-07-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailGeneration', '0004_remove_persondata_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='martial_status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='persondata',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='persondata',
            old_name='likely_investor',
            new_name='potential_investor',
        ),
    ]
